### ISSUE TITLE
@Mapper(useInjection: true) not working, implementation class not being registered

### ISSUE THREAD

**Issue by dustincatap** [smotastic/smartstruct#19] opened 2021-06-27 03:30 UTC
Given below the my mapper class:

```dart
@Mapper(useInjection: true)
abstract class UserSigninMapper {
  UserSigninContract? fromEntity(UserSigninEntity? entity);
}
```

and the generated file contains:

```dart
@LazySingleton(as: UserSigninMapper)
class UserSigninMapperImpl extends UserSigninMapper {
  @override
  UserSigninContract? fromEntity(UserSigninEntity? entity) {
    if (entity == null) {
      return null;
    }
    ;
    final usersignincontract =
        UserSigninContract(email: entity.email, password: entity.password);
    return usersignincontract;
  }
}
```

Running `flutter pub run build_runner build` shows the following output:

```
[INFO] Running build...

// Removed for brevity

[AuthManagerImpl] depends on unregistered type [UserSigninMapper] from my_app/domain/mappers/authentication/user_signin_mapper.dart

Did you forget to annotate the above class(s) or their implementation with @injectable?
------------------------------------------------------------------------ 

// Removed for brevity

[INFO] Succeeded after 19.2s with 14 outputs (90 actions)
```

It seems that `UserSigninMapper` is not being registered. I think `build_runner` is ignoring generated files.

**Comment by smotastic** [comment] 2021-06-27 07:46
Hi @dustincatap 
Correct, I didn't really think about this.
Either build_runner irgnores generated files, or the order in which the generators run matter.
If injectable runs first, my mapper.g.dart does not exist yet, and does not get registered.

Maybe we could work with something like runs_before (https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md#builderdefinition)
To tell my generator to always run before the injectable generator.

Or if nothing works, we could just use a convention in naming all the mappers, and auto-register them as described here:
https://pub.dev/packages/injectable#auto-registering

**Comment by smotastic** [comment] 2021-06-27 09:03
So i think i figured it out, it's also well explained here: 
https://github.com/dart-lang/build/issues/2701

The problem is not, that build_runner ignores generated files, but the ordering.

The solution: https://github.com/dart-lang/build/issues/2701#issuecomment-721870216
Basically injectable_generator and my smartstruct_generator are SharedPartBuilders, which means the generated code gets combined into one .g.dart file via the combining_builder.
So even if i change the ordering via runs_before, it doesn't matter because the combining builder will generate the final code in the end.
The solution is to use PartBuilder, as described in the link.
The PartBuilder will generate the code before injectable, and doesn't need to combine the code via combining_builder into one central .g.dart file.
I will now generate my own .mapper.g.dart files, which is fine i guess because i don't think we have the usecase here that multiple builders (including my mappergenerator) want to generate into one .g.dart file. Mappers are normally always their own files.
I added a flutter example project, with the new builder configuration on this branch.
https://github.com/smotastic/smartstruct/tree/bug/19_useInjectable_does_not_work

I think, now that the generated files change from .g.dart to .g.mapper.dart i have to still check the tests, and my other example project. After this i think i will release 2.0.0 as everyone is gonna have to change their already written part definitions in their mapper files.

**Comment by smotastic** [comment] 2021-06-27 20:41
Hey,
just merged a fix. https://github.com/smotastic/smartstruct/pull/20
Should work now, I also added an example specifically for injection
https://github.com/smotastic/smartstruct/tree/master/example/lib/injection

I will release 1.2.0 soon

**Closed by smotastic** 2021-06-27 20:41 UTC
